docs/getting-started/first-example/index.md
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>
=> first-example: use `reana` venv on CERN LXPLUS

docs/advanced-usage/access-control/index.md, docs/advanced-usage/index.md
Mention voms-proxy field in `Advanced usage` as well as `Access controll` next to Kerberos mention.
=> docs: mention voms-proxy next to kerberos

docs/development/releasing/index.md
* Helm releasing has been automated in https://github.com/reanahub/reana/pull/289.
=> helm: no need for releasing docs, is it automated

docs/advanced-usage/access-control/kerberos/index.md, docs/advanced-usage/access-control/voms-proxy/index.md
Add voms-proxy example to Yadage and CWL. 
At the same time I removed the `or AFS` from kerberos documentation since it might lead to confusion that you can access AFS from REANA.
=> docs: add yadage and cwl example to voms-proxy

docs/development/deploying-at-scale/index.md
* Adds a new section to hold advanced deployment scenarios such as
deploying REANA to split the system load depending on the pod type
and node labels.
=> development: split load by node labels

docs/development/deploying-locally/index.md
Amends researcher-oriented installation procedure to prefetch images,
solving installation troubles on slow network connections.
Closes reanahub/reana#431.
=> deploying-locally: prefetching images

docs/advanced-usage/compute-backends/htcondor/index.md
Add documentation and examples for `htcondor_max_runtime` and `htcondor_accounting_group`
Closes reanahub/reana-job-controller#32
=> docs: add HTC resources

docs/development/deploying-locally/index.md
Simplifies researcher-oriented installation instructions following on
the prefetching of Docker images. (It is no longer necessary to wait
for pods to be in Running state before proceeding.)
=> deploying-locally: simplification of instructions

docs/development/deploying-locally/index.md
Hi team,
While reviewing the [_Development - Deploy locally_](http://docs.reana.io/development/deploying-locally/#for-developers) guide, I noticed there are some steps duplicated. They are the ones referring to the installation of the virtual environment, and the forking/cloning of all the REANA repositories.
Happy holidays! ❄️
=> docs: remove duplicated dev. steps

docs/development/managing-users/index.md
Switches examples on how to manage users and grant tokens to use
directly executable kubectl commands. This saves the need to connect
to the individual reana-server pods beforehand.
=> managing-users: use directly executable kubectl shell commands

docs/getting-started/first-example/index.md
Without a fairly recent `pip` version, installation of `reana-client` will fail:
```
Downloading https://files.pythonhosted.org/packages/e5/b9/6cf086d8aeda6ba04abc46da724818d48578398578ec64aa39bb7bb05997/uri_template-1.1.0-py3-none-any.whl
Collecting isoduration; extra == "format" (from jsonschema[format]>=3.0.1->reana-commons<0.8.0,>=0.7.5->reana-client)
Could not find a version that satisfies the requirement isoduration; extra == "format" (from jsonschema[format]>=3.0.1->reana-commons<0.8.0,>=0.7.5->reana-client) (from versions: )
No matching distribution found for isoduration; extra == "format" (from jsonschema[format]>=3.0.1->reana-commons<0.8.0,>=0.7.5->reana-client)
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip …
```
=> Add pip upgrade command to installation instructions

docs/reference/reana-client-cli-api/index.md
- Add missing `info` command
- Use double backticks everywhere so highlighted expressions are compatible with
both markdown (docs.reana.io) and reStructuredText (reana-client.readthedocs.io)
closes #104
=> docs: update reana-client CLI API

.gitlab-ci.yml
Needed to migrate site from OpenShift 3 to OKD4 at CERN
https://how-to.docs.cern.ch/gitlabpagessite/migration/configure_repo/
=> ci: add `gitlab-ci.yml` to build mkdocs site

docs/advanced-usage/code-repositories/index.md, docs/advanced-usage/index.md, docs/advanced-usage/storage-backends/index.md
Noticed that some of the links in `Advanced usage` section are broken:
- https://docs.reana.io/advanced-usage/storage-backends/ 
- `NFS` description is not included in the index page
- `EOS` and `Shared storage` links in the index page are broken
- https://docs.reana.io/advanced-usage/code-repositories/
- links in the index page are broken
- https://docs.reana.io/advanced-usage/
- `NFS` description is not included in the index page
=> docs: fix advanced usage index links

docs/administration/deployment/deploying-locally/index.md, docs/administration/deployment/upgrading-db/index.md, docs/administration/management/managing-users/index.md, docs/advanced-usage/access-control/kerberos/index.md, docs/advanced-usage/access-control/voms-proxy/index.md, docs/advanced-usage/containers/docker/index.md, docs/advanced-usage/storage-backends/nfs/index.md, docs/getting-started/first-example/index.md, docs/running-workflows/what-is-workflow/index.md, docs/stylesheets/extra.css
- Do not copy the terminal prompt `$` when copying console snippets
- Keep the copy-to-clipboard button only for some specific snippets
Closes #120
=> docs: improve copy-to-clipboard

docs/reference/reana-yaml/index.md
Adds a note to the `reana.yaml` reference page on `inputs.directories`
to document that only non-empty directories will be seeded to the
workflow's workspace before running.
=> docs: note about non-empty inputs.directories

docs/advanced-usage/access-control/voms-proxy/index.md
Adds information about how to create job environment images so that they
would include all the necessary Grid certificates.
Refactors the other page content to improve examples and verbiage.
=> voms-proxy: info about job environment images

docs/administration/configuration/configuring-tls-certificates/index.md
Fixes a naming issue with `mycert.crt` and `mycert.key` in the TLS
documentation example code.  Addresses #131.
=> docs: fix mycert.{crt,key} example code

LICENSE, docs/administration/deployment/deploying-locally/index.md
Updates researcher-oriented installation method to use `maint-0.9` branch when fetching cluster configuration files. (Following up the recent release of REANA 0.9.0.)
=> deployment: use REANA 0.9.0 in researcher example

docs/administration/configuration/.pages, docs/administration/configuration/configuring-compute-backends/index.md, docs/administration/configuration/index.md, docs/administration/index.md
Adds administrator-related documentation on how to further customise HTCondor, Kubernetes and Slurm compute backend integration. Closes #160.
=> administration: configuring compute backends

docs/running-workflows/launching-workflows/index.md
Made the list of possible URLs more precise and made it explicit that git repositories are supported even if not hosted on GitHub.
Closes #161.
=> launching-workflows: improve description of url parameter

docs/administration/deployment/deploying-locally/index.md
I see not much value in providing a code block how to open the documentation websiter from the CLI and I would not assume everyone uses firefox. This seems the right place for good old hyperlinks to me.
=> Create inline links for dependency install doc websiter

docs/administration/configuration/configuring-interactive-sessions/index.md, docs/administration/configuration/configuring-user-quotas/index.md
Closes reanahub/reana-server#489
=> global: add missing `--admin-access-token` to `reana-admin` examples

docs/administration/configuration/configuring-access/index.md
For clarity, add a small note specifying that in order for users to
receive the confirmation email, the Helm value that enables REANA
notifications must be set to true.
Closes reanahub/reana#736.
=> administration:  add note on notifications for email confirmation

docs/reference/reana-client-cli-api/index.md
See reanahub/reana-client#716.
=> docs(cli): fix `reana-client open` command documentation typo (#204)

AUTHORS.md, docs/reference/reana-client-cli-api/index.md
Adds extra docs for `list` command to the docs for new sharing related
arguments.
Closes reanahub/reana-client#687
=> docs: add list --shared arguments

docs/getting-started/next-steps/index.md, docs/getting-started/tutorial/index.md
- docs(next-steps): advertise workflow tutorials and examples
- docs(tutorial): add link to HSF training
Closes #143 #171
=> docs(tutorial): add link to HSF training
