reanahub/docs.reana.io

.travis.yml
README.md
requirements.txt

Addresses https://github.com/reanahub/docs.reana.io/pull/3#discussion_r359218831

readme: add running steps

---

docs/advanced-usage/access-control/kerberos/index.md
docs/advanced-usage/code-repositories/cvmfs/index.md
docs/advanced-usage/compute-backends/htcondor/index.md
docs/advanced-usage/compute-backends/kubernetes/index.md
docs/advanced-usage/compute-backends/slurm/index.md

advanced: adds K8s, HTCondor & Slurm docs

---

docs/advanced-usage/storage-backends/eos/index.md

eos: adds docs

---

docs/reference/reana-yaml/index.md

referece: adds reana.yaml docs

---

docs/reference/reana-yaml/index.md

* Expands Reference section guide on `reana.yaml` using more technical
language. (closes #21)
Signed-off-by: Tibor Šimko <tibor.simko@cern.ch>

reference: reana.yaml updates

---

docs/stylesheets/extra.css

style: custom note boxes and code highlighting

---

docs/advanced-usage/storage-backends/nfs/index.md
docs/development/deploying-at-scale/index.md
docs/development/deploying-locally/index.md
docs/development/releasing/index.md
docs/index.md

development: how to deploy REANA

---

docs/advanced-usage/access-control/voms-proxy/index.md

Currently only for serial. Not sure if field `Testing your credentials` is necessary?
closes  reanahub/docs.reana.io#36

voms-proxy: add docs for using voms_proxy field

---

.travis.yml
docs/development/deploying-at-scale/index.md
docs/development/index.md
docs/development/managing-users/index.md

* Addresses reanahub/reana-server#235.

development: manage users documentation

---

docs/development/deploying-at-scale/index.md

- Addresses reanahub/reana#274

deploy: configurable namespace at deployment time

---

docs/reference/reana-yaml/index.md

reana.yaml: add operations options section

---

docs/getting-started/first-example/index.md
docs/reference/reana-client-cli-api/index.md
docs/reference/reana-client-python-api/index.md

docs: point to autogenerated CLI API docs

---

docs/development/deploying-locally/index.md
docs/development/managing-users/index.md

According to https://github.com/reanahub/reana-server/pull/274/commits/63c60079ec11e3ad0d0e776c1c34dfff8977ad6b

users: harmonise reana-admin commands

---

docs/reference/reana-client-cli-api/index.md

closes reanahub/reana-client#424

docs: add quota-show CLI commands

---

docs/reference/reana-client-cli-api/index.md

Removal of hard deletion from examples.
closes reanahub/reana-client#436

docs: update reana-client delete command

---

docs/reference/reana-client-cli-api/index.md

* Closes reanahub/reana-server#296.

docs: add reana-client's human-readable option

---

docs/administration/deployment/index.md

docs: added deployment index page

---

docs/administration/deployment/deploying-at-scale/index.md

deploying: node labels to split runtime components

---

docs/advanced-usage/compute-backends/kubernetes/index.md

- Add usage of kubernetes_memory_limit
closes https://github.com/reanahub/reana-client/issues/496

docs: Add Custom memory limit resources

---

docs/administration/configuration/configuring-scheduler/index.md
docs/administration/configuration/index.md
docs/administration/index.md

closes https://github.com/reanahub/reana-server/issues/357

configuration: added configuring workflow scheduler page

---

docs/reference/reana-client-cli-api/index.md
docs/reference/reana-yaml/index.md

closes https://github.com/reanahub/reana-client/issues/536

docs: add outputs.directories in reana.yaml

---

docs/reference/reana-yaml/index.md

closes reanahub/reana-commons#284
closes reanahub/reana-commons#288

docs: add snakemake `report` operational option

---

docs/administration/deployment/deploying-locally/index.md
mkdocs.yml

- add some help with `reana-dev` for **conda** users
- add some help with `reana-dev git-fork for macOS users

docs: improve description of deploying-locally page

---

docs/administration/deployment/deploying-at-scale/index.md
docs/administration/deployment/deploying-locally/index.md
docs/administration/deployment/index.md
docs/administration/deployment/upgrading-db/index.md
docs/administration/index.md
docs/index.md

addresses https://github.com/reanahub/reana/issues/591

admin: add upgrading database section

---

docs/advanced-usage/compute-backends/kubernetes/index.md

closes reanahub/reana-job-controller#343

kubernetes: add job_timeout docs section

---

docs/running-workflows/supported-systems/cwl/index.md

closes https://github.com/reanahub/docs.reana.io/issues/99

docs: added CWL conformance results

---

docs/reference/reana-client-cli-api/index.md

Related to reanahub/reana-client#592

docs: update download command of reana-client

---

docs/running-workflows/supported-systems/serial/index.md
docs/running-workflows/supported-systems/snakemake/index.md
docs/running-workflows/supported-systems/yadage/index.md

closes https://github.com/reanahub/docs.reana.io/issues/101

docs: improved supported workflow systems

---

docs/advanced-usage/compute-backends/slurm/index.md

closes https://github.com/reanahub/reana-job-controller/issues/206

slum: specifying partition and timelimit

---

docs/reference/reana-client-cli-api/index.md

closes reanahub/reana-client#614

reana-client: update "delete" command docs

---

docs/administration/configuration/configuring-access/index.md
docs/advanced-usage/access-control/kerberos/index.md
docs/reference/reana-yaml/index.md

Closes reanahub/reana-workflow-engine-snakemake#44

docs: describe how to set up Kerberos globally

---

docs/reference/reana-client-cli-api/index.md

Closes reanahub/reana-workflow-controller#469

docs: update reana-client mv command

---

docs/advanced-usage/access-control/index.md
docs/advanced-usage/access-control/rucio/index.md
docs/advanced-usage/containers/docker/index.md
docs/advanced-usage/index.md

Closes reanahub/reana-auth-rucio#1.

rucio: add support

---

README.md
docs/advanced-usage/access-control/voms-proxy/index.md

Enriches VOMS proxy usage documentation about two approaches, the client-side and the server-side VOMS proxy file generation, with their pros and cons. Closes reanahub/reana-auth-vomsproxy#16.

docs: client-side vs server-side VOMS proxy

---

docs/reference/reana-client-cli-api/index.md

closes https://github.com/reanahub/reana-client/issues/637

docs: update reana-client secrets commands

---

docs/reference/reana-client-cli-api/index.md

Closes reanahub/reana-client#620

docs: add reana-client retention-rules-list command

---

docs/reference/reana-client-cli-api/index.md

Closes reanahub/reana-client#651

cli: add prune command

---

docs/advanced-usage/access-control/kerberos/index.md

Updates keytab generation instructions following KB0003405. Closes #173.

kerberos: fix keytab generation instructions

---

docs/administration/configuration/.pages
docs/administration/configuration/configuring-private-docker-registries/index.md
docs/administration/configuration/index.md
docs/administration/index.md
docs/advanced-usage/access-control/private-docker-registries/index.md

administration: add configuration of private registries

---

docs/administration/configuration/configuring-compute-backends/index.md
docs/administration/configuration/configuring-storage-volumes/index.md
docs/advanced-usage/access-control/kerberos/index.md
docs/advanced-usage/access-control/rucio/index.md
docs/advanced-usage/access-control/voms-proxy/index.md
docs/advanced-usage/code-repositories/cvmfs/index.md
docs/advanced-usage/compute-backends/kubernetes/index.md
docs/advanced-usage/compute-backends/slurm/index.md
docs/advanced-usage/containers/docker/index.md
docs/advanced-usage/storage-backends/eos/index.md

Adds fully qualified canonical locations of container images, making the container technology setup podman-friendly.
Closes reanahub/reana#729.

docker: podman-friendly image locations

---

docs/advanced-usage/access-control/private-docker-registries/index.md

Improves verbiage of the Private Docker registries documentation page.

access-control: enhance private Docker registries

---

docs/administration/configuration/configuring-cluster-ingress/index.md

docs(ingress): avoid deprecated annotation to set ingress class (#203)

---

docs/reference/reana-client-cli-api/index.md

Related to https://github.com/reanahub/reana/issues/824
Update docs of logs command after creating --follow flag.

docs(cli): update reana-client-cli-api logs (#210)

---

docs/administration/configuration/configuring-storage-volumes/index.md

docs(configuring-storage-volumes): fix shared volume mix-up (#217)
